### ISSUE TITLE
Connection Error: using KeyBERT with a proxy?

### ISSUE THREAD

**Issue by NMoro811** [MaartenGr/KeyBERT#100]
Goedenavond, team! 

First of all, great work with the library. I have been playing around with it in my free time for some small projects and it works like a charm. However, when I try simply creating a KeyBert() object in a notebook for a project at work, I keep getting the following connection error:

ConnectionError: HTTPSConnectionPool(host='[huggingface.co](http://huggingface.co/)', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000280691D0E08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

I think this is most likely due to the firewall we have in place since a proxy is usually needed to download external packages, for instance. Is there any way to fix this issue by connecting via the proxy without having to modify the source code? 

Thanks in advance for your time!

**Comment by MaartenGr** [comment]
> Goedenavond, team!

Geweldig! One of the few times seeing someone using Dutch here :-)

> I think this is most likely due to the firewall we have in place since a proxy is usually needed to download external packages, for instance. Is there any way to fix this issue by connecting via the proxy without having to modify the source code?

Yes, my guess would indeed be something going on with your connection and a firewall would make sense. A while ago there was a similar question regarding BERTopic and you can find the solution I posted [here](https://github.com/MaartenGr/BERTopic/issues/186#issuecomment-884767418). Basically, instead of downloading the transformer model when running SentenceTransformer, you can also down the model beforehand and upload that to your server. Then, you can load it locally instead of requiring a working connection.

**Comment by NMoro811** [comment]
Hi! Forgot to close the issue. This worked great. Thanks!
