### ISSUE TITLE
Not getting scores displayed in newest version

### ISSUE THREAD

**Issue by NMoro811** [MaartenGr/KeyBERT#105]
Hoi!

My question is rather quick: I have upgraded KeyBERT to the newest version yet when I use extract_keywords in a document I only get a list of strings instead of tuples with the scores. Essentially, the same problem as #59 but the fix didn't solve it for me. Any other reason why it might not be working?

**Comment by MaartenGr** [comment]
Since you are having the same issue, I would advise starting from a fresh environment and installing KeyBERT as follows: `pip install keybert`. Make sure you do not install it as follows: `pip install keybert[all]` as that will try to find an earlier version of KeyBERT. Then, you can make sure you have installed the latest version of KeyBERT with `pip freeze`. 

It does seem that you do not have the latest version of KeyBERT installed. Could you do a `pip freeze` to check out which version you have installed?

**Comment by NMoro811** [comment]
Hi again! I'm not sure what it was, but reinstalling KeyBERT did work, even if pip freeze showed the correct version. Perhaps there was a compatibility problem. Anyways, thanks again for your help!
