### ISSUE TITLE
Class of KeyBERT

### ISSUE THREAD

**Issue by pandalalalala** [MaartenGr/KeyBERT#11]
Hi Marrten!

Would it make the code more coherent if you let your KeyBERT inherit the class of your favorite SentenceTransformer?

Thank you.

**Comment by MaartenGr** [comment]
Hi! 

I am not sure. I believe doing so would result in the user also having to import the `SentenceTransformer` package separately from keyBERT while I think it would be more coherent if that part is in KeyBERT itself. 

It would be nice though if the user could specify any transformer model to be used for keyword extraction although that would require some significant changes it might be interesting to look at. Perhaps using `Flair` instead of `SentenceTransformer` would solve that issue.
