### ISSUE TITLE
Maarten should accept sponsorships

### ISSUE THREAD

**Issue by tylerexpa** [MaartenGr/KeyBERT#119]
Hey @MaartenGr ,

You're doing a lot of great work.  I'm really impressed with how well you've put several of these repositories together.  You should consider accepting github sponsorships.  100% of the sponsorship goes to the sponsoree.  $5 from a hundred people every month adds up to A LOT of lattes :)

**Comment by tylerexpa** [comment]
closing just to not clutter the board

**Comment by MaartenGr** [comment]
Sorry for the late response! Thank you for suggesting this. I am working on these repos whenever I can outside of work and I am hesitant to accept sponsorships due to my sporadic time working on it all. If I ever decide to pursue this a bit more full-time, then I will definitely consider accepting sponsorships.
