### ISSUE TITLE
Compatibility Issues with MacBook M1 due to dependency on  Tokenizers < 0.13.0

### ISSUE THREAD

**Issue by KMFODA** [MaartenGr/KeyBERT#134]
Hello, I was struggling to get this library loaded on an M1 MacBooks because the tokenizers library could not be automatically built for M1s. Tokenisers 0.13.0 [now supports this](https://github.com/huggingface/tokenizers/issues/712#issuecomment-1259638471) but KeyBert still has a dependency on tokenizers < 0.13.0.

I wanted to understand what main feature requires this dependency and if we can work to remove it somehow.

**Comment by MaartenGr** [comment]
There is not an explicit dependency in BERTopic on Tokenizers 0.13.0, most likely this is capped in SentenceTransformers, since that is the only one that, aside from the extra requirements, has a dependency on Tokenizers. Having said that, reading its [requirements](https://github.com/UKPLab/sentence-transformers/blob/master/requirements.txt), it seems it does not explicitly cap the version of Tokenizers.

**Comment by KMFODA** [comment]
Oh I see. Creating a new environment and installing the latest version of tokenisers then KeyBert seemed to fix this for me. Thanks for the help!
