### ISSUE TITLE
Not showing the ".",dot, in console when I was trying to highlight the doc through .extract_keywords

### ISSUE THREAD

**Issue by sabin5105** [MaartenGr/KeyBERT#157]
I found  the ".", dot, is not showing in console when I was trying to highlight the doc through .extract_keywords.

I guess this is why The CounterVectorizer's tokenizer splits a string of text into tokens based on whitespace and punctuation by default. The "." (period) is considered as a punctuation and is used to split the text into separate tokens. 

maybe I could add some parameters in highlight function below which could control the issue by an customized one? https://github.com/MaartenGr/KeyBERT/blob/f91c5022d192df242043a19511d69714e71cb81c/keybert/_highlight.py#L14

please let me know this is the issue that was confronted before,
or maybe you already know it but you don't think it doesn't need to fix?

the console output be like this

```python
kw_model.extract_keywords(doc, keyphrase_ngram_range=(2, 2), stop_words='english',
                              use_mmr=True, diversity=0.5, highlight=True)
```
```console
#output
Supervised learning the machine learning task of learning function maps an input to an output based on example 
input output pairs It infers function from labeled training data consisting of set of training examples In 
supervised learning example is pair consisting of an input object vector and desired output value also called the 
supervisory signal learning algorithm analyzes the training data and produces an inferred function which can be 
used for mapping new examples An optimal scenario will allow for the algorithm to correctly determine the class 
labels for unseen instances This requires the learning algorithm to generalize from the training data to unseen 
situations in reasonable way see inductive bias
[('supervised learning', 0.6538),
 ('learning function', 0.5619),
 ('function labeled', 0.384),
 ('supervisory signal', 0.3386),
 ('input object', 0.2421)]
```

**Comment by MaartenGr** [comment]
The difficulty here is that in order to highlight the corresponding tokens, it is necessary to make use of the tokenizer in KeyBERT. For example, the tokenizer might remove stopwords and as a result, will not highlight some of the keyphrases in the original text as that might include stopwords. In other words, using the tokenizer it is possible to go from text to tokens but it is not possible to go from tokens to the original text. As such, there will be things missing in the highlighted text. 

I am actually not sure if it is possible with minimal code to easily perform highlighting on the original text, including dots as the structure of languages can differ greatly. That is why I prefer to use the tokenizer as that is language-dependent and nothing needs to be built on top.
