### ISSUE TITLE
Dutch

### ISSUE THREAD

**Issue by gevezex** [MaartenGr/KeyBERT#36]
Hi Maarten,

As you are dutch, what is your take on dutch embeddings. What is your experience with dutch models (which model gives the best results for example for KeyBert? 
Bertje is the dutch Bert model but for sentence embeddings there is no trained Bertje-sentence model. Did you experiment with it? I am really interested in your experience.

**Comment by MaartenGr** [comment]
Sorry for the late response! I am actually a big fan of FastText embeddings for shorter texts and/or shorter keyphrases since they typically capture the semantic meaning of words quite well. You can use [Bertje](https://github.com/wietsedv/bertje) but it was not specifically trained for semantic similarity and might not give the results you are looking for. I would advise starting out with dutch FastText embeddings and if that does not work, use a multi-lingual model in sentence-transformers.
