### ISSUE TITLE
int too big to convert

### ISSUE THREAD

**Issue by Syavaprd** [MaartenGr/KeyBERT#40]
Hello, when I extract_keywords, I get the following result: OverflowError: int too big to convert.
I follow the example from this link.
https://datatalk.info/post/2021/04/27/scientific-keyword-extraction-with-scibert-and-keybert

**Comment by MaartenGr** [comment]
Wow, my apologies for this extremely late response. I typically try to respond within a few days 😅

That error, to my knowledge, can be due to two things: either KeyBERT was incorrectly installed or the embedding model has a token limit. Keeping that in mind I would try it out again in a fresh environment and see what happens. KeyBERT has since been updated which could have fixed the issue. If that does not work, try removing some of the larger documents as they might exceed the embedding model's token limit.

**Comment by MaartenGr** [comment]
I will close this for now seeing as there hasn't been an update. However, feel free to re-open it if you are still experiencing this issue!
