### ISSUE TITLE
Usage on large documents 

### ISSUE THREAD

**Issue by vishruthdilip** [MaartenGr/KeyBERT#64]
Can anyone explain in detail how this can be used with very large text documents?

**Comment by MaartenGr** [comment]
This depends on your definition of "very large text documents". BERTopic can handle paragraphs and even several pages of documents (through TF-IDF embeddings instead of transformer-based embeddings) but it all depends on what the documents are expected to contain. 

If you expect that each very large text document contains multiple topics, I would highly advise splitting them up into either sentences or paragraphs. You can then feed those to BERTopic and simply count yourself how frequent certain topics are in certain documents. Typically, this would be the preferred method.

**Comment by vishruthdilip** [comment]
No problem. So from what I understand you suggest extracting keywords for each sentence, and then picking out the words that occur most frequently in these ~40,000 sentences? Is this the most efficient way to do it? 

As you mention in your blog the sentence transformer models have a token limit and you suggest mean pooling to get the average vectors. 
I wanted to know how I can do that.

**Comment by Manel-Hik** [comment]
Hi 
I was testing Keybert on large document (wikipedia articles) to extract keywords, it seems that it needs more resources than I thought. especially when applying it on the whole dataframe (5500 articles with different topics)
Could anyone faced same point?
Is there a tip to make it faster?
Thanks

**Comment by MaartenGr** [comment]
For large documents, you will need an embedding model that supports that. In practice, large documents are not supported by sentence-transformers which could slow down inference and reduce the quality of the output. I would advise splitting up the documents into paragraphs and then performing keyword extraction.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. As always, if you want to discuss this issue further, let me know and I'll reopen the issue!
