### ISSUE TITLE
Parsing multiple documents?

### ISSUE THREAD

**Issue by millnerryan** [MaartenGr/KeyBERT#75]
I have ~100 documents (each a few sentences in length) that I'm using KeyBERT to extract keywords.  This is part of a UI I'm building, so while it's not in the runtime path it does need to be fast as users will repeatedly interact with this function.

Currently, I'm looping through each, extracting keywords using KeyBERT, then combining these outputs and selecting the most common keywords. Right now it takes ~6 seconds. From the documentation, it says `Multiple Documents: There is an option to extract keywords for multiple documents that is faster than extraction for multiple single documents.`

Is this a parameter I'm not seeing somewhere, or does this just mean that I can pass a list of documents for `docs`? If it's the latter, how does this work? Does it simply combine all of these items in the list together and treat that as one big document?

**Comment by MaartenGr** [comment]
You are correct in that you can simply pass a list of documents for `docs`. That will automatically use the method but is typically not advised. 

It extracts all words from all documents so that each word only needs to be embedded once. Then, it compares the cosine similarity between word embeddings in the document and the document itself. It will not, however, run MMR or Max Sum Sim.

**Comment by millnerryan** [comment]
thanks!
