### ISSUE TITLE
Some stopwords didn't  be removed

### ISSUE THREAD

**Issue by boa19941212** [MaartenGr/KeyBERT#85]
Hello, thank you for incrediable KeyBert!
I have few questions need to ask, i am using chinese dataset, and custom chinese vectorizer now,
however when i  get ouput  keywords results from KeyBert, i found that there are many stopwords are be included.  

When I remove stopwords before use KeyBert rather than input stopwords into vectorizer ,the keywords results look good.
Now I am confused about the priority of  excuting code. 

Could you help me figure out this problem? Thank you!

**Comment by MaartenGr** [comment]
Apologies for the late reply! 

Could you share the code that you have been using thus far? Perhaps there was an issue with the choice of embedding model. Typically, you should not get stopwords in the output but that might also depend on the vectorizer, embedding model, and documents that you use.

**Comment by boa19941212** [comment]
Hello here is my code, thank you.

```python

def clean_and_cut(x):
#ws() is a word segmentation tool
    x = [word for word in ws([x],coerce_dictionary =dic)[0] if word not in stopword_list and len(word)>1 and word.isalpha()]
#     x = ws([x],coerce_dictionary=dic)[0] #without remove stopwords
    return x

k_vectorizer = CountVectorizer(tokenizer=clean_and_cut)

sentence_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
kw_model = KeyBERT(model=sentence_model)

keywords = kw_model.extract_keywords(doc, stop_words= stopword_list, nr_candidates = 20,
                                      top_n=20,use_mmr=True, diversity=0.7,vectorizer=k_vectorizer)

```

**Comment by MaartenGr** [comment]
The diversity is set quite high and might explain why some stopwords were set in the output. It might do this in order to create enough diversity, so lowering this could make a difference. Second, you do not need to use `nr_candidates` if you if use MMR, so I would suggest removing that parameter. Lastly, could you also try out `jieba` for tokenizing the document as described [here](https://maartengr.github.io/KeyBERT/faq.html#how-can-i-use-keybert-with-chinese-documents)? I am not familiar with the word segmentation tool that you used and thus far jieba has been working well.

**Comment by boa19941212** [comment]
Because jieba tool did't work well on my data,  thank you for response! I will try your suggestion later!

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. However, if you are experiencing this issue still, I'll make sure to reopen the issue and we can discuss it further.
