### ISSUE TITLE
MMR reranking of sentences?

### ISSUE THREAD

**Issue by pablogranolabar** [MaartenGr/KeyBERT#86]
Hi,

Thanks for making KeyBERT available, great solution for topic modeling.

Question: I am curious if KeyBERT has an accessible MMR implementation for reranking of sentences. For example, if I have a summarization model with beam output of say 20 summary sentences from analyzing a larger document (in chunks to deal with token input window limitations on the transformer), would MMR be a viable approach for reranking those 20 sentences in order to retrieve the top 5 most diverse results that share semantic similarity?

Thanks in advance

**Comment by MaartenGr** [comment]
I think this should be possible. You can access the MMR module through `from keybert._mmr import mmr` and then use it something like this:

```python
output_sentences = mmr(doc_embedding, candidate_sentence_embeddings, candidate_sentences, top_n=5, diversity=0.1)
```

Here, `doc_embedding` is the embedding of your larger document so that would be a vector of size *n*, where *n* is the embedding size of your embedding model (e.g., 384). `candidate_sentence_embeddings` are the embeddings of each of the sentences which is a matrix of size *m* * *n*, where *m* is the number of sentences (in this case 20), so in this example that would be 384 * 20. `candidate_sentences` are simply the sentences in order. 

You can find a bit more about that method [here](https://github.com/MaartenGr/KeyBERT/blob/master/keybert/_mmr.py). It is a relatively straightforward method and I think the above along with the link should get you started.

**Comment by pablogranolabar** [comment]
Thanks @MaartenGr, this is perfect!
