### ISSUE TITLE
Basic questions 

### ISSUE THREAD

**Issue by peterelbert** [MaartenGr/KeyBERT#87]
Thanks for this great tool.

A few things I’m trying to understand:

We specify the number of keywords returned with nr_candidates? (I.e., 1000 keywords?) Does this work independently of Max Sum Similarity or only in conjunction with it?

We select phrases of varying length with keyphrase_ngram_range=(n,m)? This will return phrases of n min, m max words?

I noticed there is some advice for diversifying the results. Is there any advice on when you choose to use this technique? Does it depend on the situation, so you first try BERT in the default way and then try diversification if necessary?

What’s the function of the stop word? I couldn’t understand why you would wish to stop on a word, such as “English”.

What specs of a machine do you recommend for fast performance? I’m using a Digital Ocean Droplet and I’d love to have this work as fast as possible. How many cores in a CPU do you expect could bring a 1000-keyword extraction down to about a second long? Or is the GPU more important or anything? What’s your preferred remote machine service for an affordable GPU for running KeyBERT?

Thank you very much

**Comment by MaartenGr** [comment]
Thank you for the kind words!

> We specify the number of keywords returned with nr_candidates? (I.e., 1000 keywords?) Does this work independently of Max Sum Similarity or only in conjunction with it?

You can use `top_n` to select the number of keywords that are returned. `nr_candidates` is used only for Max Sum Similarity and is simply the number of candidates to consider. If you set this value too high, the application might slow down significantly and the quality might degrade. 

> We select phrases of varying length with keyphrase_ngram_range=(n,m)? This will return phrases of n min, m max words?

Yes, `keyphrase_ngram_range` is used to select the minimum and maximum length (in words) of the keywords/keyphrases that are returned. 

> What’s the function of the stop word? I couldn’t understand why you would wish to stop on a word, such as “English”.

Stop words are words that typically have little meaning and appear quite frequently in text, such "a", "the", and "of". We can use `stop_words="english"` to remove those stopwords from the text such that they do not end up in the keyphrases. 

> What specs of a machine do you recommend for fast performance? I’m using a Digital Ocean Droplet and I’d love to have this work as fast as possible. How many cores in a CPU do you expect could bring a 1000-keyword extraction down to about a second long? Or is the GPU more important or anything? What’s your preferred remote machine service for an affordable GPU for running KeyBERT?

Typically, I would advise using a GPU as the embeddings are often transformer-based and have a major speed-up compared to a CPU. It is difficult to say which GPU or how many cores a CPU might need since KeyBERT allows for a variety of embedding models to be used, ranging from sentence-transformers to USE (universal sentence encoder).

**Comment by MaartenGr** [comment]
Unfortunately, it is a bit more complicated than that. There are quite a few things it depends on and there is not a straightforward formula for calculating how long processing might take. If you want to speed up the application, you can either shorten the text by removing stopwords or words that are of no interest to you, use a better-performing GPU, or use a faster embedding model.

**Comment by peterelbert** [comment]
Thanks. So flair and gensim are examples of different models? Which one is fastest?

I tried KeyBERT on about three large paragraphs of text from Wikipedia in the free version of Google Colab and asked it to get 3 keywords. It took 41 seconds. For my purposes, it’ll need to be much faster. I’d prefer just a few seconds, ideally.

I’ll next be exploring using faster GPUs and removing stop words.

Thanks very much
